id: P006615
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG5871
  title: ལུགས་བརྒྱ་པ།
  author: ''
  volumes:
    0bd4446151cc4032bae19e3625fc24a8:
      image_group_id: I1KG5889
      title: ''
      volume_number: 1
      total_pages: 112
      base_file: v001.txt
